import { defineCollection, z } from 'astro:content';

// ── Projects ────────────────────────────────────────────────────────────────
const projects = defineCollection({
  type: 'content',
  schema: z.object({
    title:     z.string(),
    // slug is auto-generated by Astro from the filename; not in schema
    summary:   z.string().max(200),
    date:      z.coerce.date(),
    techStack: z.array(z.string()),
    links: z
      .object({
        github: z.string().url().optional(),
        demo:   z.string().url().optional(),
        blog:   z.string().optional(),
      })
      .optional(),
    thumbnail: z.string().optional(),
    featured:  z.boolean().default(false),
  }),
});

// ── Writing ─────────────────────────────────────────────────────────────────
const writing = defineCollection({
  type: 'content',
  schema: z.object({
    title:   z.string(),
    // slug is auto-generated by Astro from the filename; not in schema
    date:    z.coerce.date(),
    summary: z.string(),
    tags:    z.array(z.string()).optional(),
  }),
});

// ── Work ─────────────────────────────────────────────────────────────────────
const work = defineCollection({
  type: 'content',
  schema: z.object({
    org:         z.string(),
    role:        z.string(),
    startDate:   z.coerce.date(),
    // null = current role; omit field entirely for past roles
    endDate:     z.coerce.date().nullable().optional(),
    description: z.string(),
    techStack:   z.array(z.string()).optional(),
    location:    z.string().optional(),
  }),
});

export const collections = { projects, writing, work };
